"""Drop snsId

Revision ID: 12e68a05089a
Revises: 3130068affd2
Create Date: 2015-07-26 00:28:59.072320

"""

# revision identifiers, used by Alembic.
revision = '12e68a05089a'
down_revision = '3130068affd2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'snsId')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('snsId', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
