"""Add quarantined field to User

Revision ID: 3130068affd2
Revises: 3bc87eea6e87
Create Date: 2015-07-20 22:53:55.369560

"""

# revision identifiers, used by Alembic.
revision = '3130068affd2'
down_revision = '3bc87eea6e87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('quarantined', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'quarantined')
    ### end Alembic commands ###
