"""empty message

Revision ID: 556de9c727e3
Revises: None
Create Date: 2015-07-20 01:51:22.509129

"""

# revision identifiers, used by Alembic.
revision = '556de9c727e3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('deviceToken', sa.Unicode(length=64), nullable=True),
    sa.Column('snsId', sa.String(), nullable=True),
    sa.Column('untappdEnabled', sa.Boolean()),
    sa.Column('swarmEnabled', sa.Boolean()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foursquareToken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('untappdToken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('untappdToken')
    op.drop_table('foursquareToken')
    op.drop_table('user')
    ### end Alembic commands ###
